version: "3"

services:
  web:
    build: .
    volumes:
      - ./rooaa/images/:/usr/src/app/rooaa/images/
    command: python3 manage.py -p

    depends_on:
      - dense_service
      - yolo_service
    ports:
      - "5000:5000"

  yolo_service:
    build: .
    volumes:
      - ./rooaa/images/:/usr/src/app/rooaa/images/
    command: python3 MLService/yolo_service.py
    ports:
      - "5001:5001"

  dense_service:
    build: .
    volumes:
      - ./rooaa/images/:/usr/src/app/rooaa/images/
    command: python3 MLService/dense_service.py
    ports:
      - "5002:5002"
